### ISSUE TITLE
Request for data source of this provider

### ISSUE THREAD

**Issue by sgabenov** [bendrucker/terraform-provider-dns-validation#6]
Hi there,

Would it be possible to add a "data source" resource for your provider? 
In scenario with using resource type it creates a resource when DNS name exists and fails a deploy when resource is absent. 

But sometimes we just need to check if DNS name exists or not. If not exist - run null_resource script to create a new DNS CNAME record in our workflow. And in this case we do not want to FAIL deployment, but check if data source exist or changed.
So it should look like this:

```
data "dns_address_validation" "infoblox_dns_exist" {
  provider = dns-validation
  name = "example-exist.mydomain.net"
}

data "dns_address_validation" "infoblox_dns_not_exist" {
  provider = dns-validation
  name = "example-fail.mydomain.net"
}
```

which will generate a state like this:
```
# data.dns_address_validation.infoblox_dns_exist["example-exist.mydomain.net"]:
data "dns_address_validation" "infoblox_dns_exist" {
    id   = "example-exist.mydomain.net"
    name = "example-exist.mydomain.net"
    status = dns_exist   // or just "True"
}

# data.dns_address_validation.infoblox_dns_not_exist["example-fail.mydomain.net"]:
data "dns_address_validation" "infoblox_dns_not_exist" {
    id   = "example-fail.mydomain.net"
    name = "example-fail.mydomain.net"
    status = dns_not_exist  // or just "False"
}
```

**Comment by bendrucker** [comment]
Would this not be suitable?

https://registry.terraform.io/providers/hashicorp/dns/latest/docs/data-sources/dns_cname_record_set

It might error if the lookup fails but you could easily fork and modify that behavior so that `cname = ""` when no record is found. The purpose of this provider is to deal with asynchronous updates to DNS, where one Terraform resource updates a record (e.g. `aws_route53_record`) and then another resource intends to consume/query that record. I'm not really inclined to add unrelated DNS query features.
